---
# ######################################### Basic Parameters #######################################

# Scale factor
scale_factor: 1

# Profiler
profile: False
pstats_records: 100

# Random seeds for each region
random_seed: 1

# Enable or disable the use of parallel processing. Note that the number of jobs is automatically
# reset according to the number of regions and population ratio between regions:
enable_parallel: True
num_jobs: -2

# ######################################### Clock ##################################################

# Time length of each tick in the simulation. The day length (86400) should be divisible by the
# following tick length:
tick_length_s: 3600
# How long the simulation should run for, in days. Note the number of iterations will be computed
# from the tick length above:
simulation_length_days: 100
# the date at which the simulation starts:
epoch: 23rd February 2020

# ######################################### World ##################################################

world_factory:
  __type__: colombia_world_factory.ColombiaWorldFactory
  regions_shape_path: Scenarios/Wales/data/localauthorities_lwm.shp
  regions_data_path: Scenarios/Wales/data/country_data.csv
  contacts: 5
  contact_hours: 8
  local_travel_prob_per_day: 0.01
  distance_threshold: 1

# ######################################### Seasonal Effects #######################################

seasonal_effects_model:
  __type__: void_seasonal_effects_model.VoidSeasonalEffectsModel

# ######################################### Health #################################################

health_model:
  __type__: default_health_model.DefaultHealthModel
  beta: [1.0]
  location_typ_multipliers: null
  facemask_transmission_multiplier: 1.0
  immunity_period_days: 30
  num_initial_infections_by_region_by_strain:
    'Cardiff': [1000]
  mutation_matrix: [[1.0]]
  number_of_strains: 1
  preexisting_sigma_multiplier: 1.0
  preexisting_rho_multiplier: 1.0
  country_data_sigma_immunity_fp: null
  country_data_rho_immunity_fp: null
  preset_weights_by_age:
    0:  {preset_0: 1.00}
  health_presets:
    preset_0:
      0:
        rho_immunity_failure:
          [[[[-1, 9, 365], [[0.0], [0.0], [0.0]]]]]
        sigma_immunity_failure:
          [[[[-1, 9, 365], [1.0, 0.0, 1.0]]]]
        infectiousness:
          [[[-1, 0, 9], [0.0, 0.27, 0.0]]]
        disease:
          [[[-1, 0, 9], [0.0, 0.2, 0.0]]]
        strain:
          [[[-1, 0, 9], [-1, 0, -1]]]
  # Rescale by time and population in each location, deactivate by setting sir_rescaling = False
  sir_rescaling: True
  # Deactivate by setting age_mixing_matrices = null
  age_mixing_matrices: null
  age_group_interval: null
  # Deactivate by setting auto_generate_presets = False
  auto_generate_presets: False
  sir_beta: null # Units: days^{-1}
  sir_gamma_inverse: null # Units: days
  sir_disease_level: null
  sir_max_dist_days: null # Maximum infectiousness period, curtailing the geometric distribution 

# ######################################### Movement ###############################################

movement_model:
  __type__: void_movement_model.VoidMovementModel

# ######################################### Hospitalization and Death ##############################

hospitalization_and_death_model:
  __type__: void_hospitalization_and_death_model.VoidHospitalizationAndDeathModel

# ######################################### Testing and Contact Tracing ############################

testing_and_contact_tracing_model:
  __type__: void_testing_and_contact_tracing_model.VoidTestingAndContactTracingModel

# ######################################### Vaccination ############################################

vaccination_model:
  __type__: void_vaccination_model.VoidVaccinationModel

# ######################################### Regional Mixing ########################################

regional_mixing_model:
  __type__: default_regional_mixing_model.DefaultRegionalMixingModel
  travel_transmission_multiplier: 1.0

# ######################################### Input ##################################################

input_model:
  __type__: void_input_model.VoidInputModel

# ######################################### Output #################################################

regions_omitted_from_death_counts: []
super_regions_omitted_from_deaths_counts: []
historical_data_filepath: null

# Output that should be rendered from the simulation:
reporters:
  cli.TimeReporter: {}
  csv.StrainCounts:
    filename: /tmp/strain_counts_wales.csv
  plot.PlotInfected:
    show: False
    savefig: True
    filename: /tmp/infected_wales.png
    historical_data: null
  pygame_shapes.PygameShapes:
    fullscreen: False
    font_size: 20
    max_norm_prev: 1.0
    refresh_rate: 60
    display_width: 600
    display_height: 600
    points_per_polygon: 600
    cmap: "Oranges"

# ######################################### Logging ################################################

# Format is https://docs.python.org/3/library/logging.config.html#logging-config-dictschema
logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    standard:
      # format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
      format: '[%(levelname)s] %(name)s: %(message)s'
  handlers:
    default:
      level: INFO
      formatter: standard
      class: logging.StreamHandler
      stream: 'ext://sys.stdout'  # Default is stderr
  loggers:
    '':   # root logger
      handlers: ['default']
      level: INFO
      propagate: False
#    'my.packg':
#      handlers: ['default']
#      level: INFO
#      propagate: False
#    '__main__':
#        handlers': ['default']
#        level: DEBUG
#        propagate: False
