---
# ######################################### Basic Parameters #######################################

# Scale factor
scale_factor: 1.0

# Profiler
profile: False
pstats_records: 100

# Random seeds for each region
random_seed: 1

# Enable or disable the use of ctypes
enable_ctypes: True

# Enable or disable the use of parallel processing. Note that the number of jobs is automatically
# reset according to the number of regions and population ratio between regions:
enable_parallel: False
num_jobs: -2

# ######################################### Clock ##################################################

# Time length of each tick in the simulation. The day length (86400) should be divisible by the
# following tick length:
tick_length_s: 86400
# How long the simulation should run for, in days. Note the number of iterations will be computed
# from the tick length above:
simulation_length_days: 365
# the date at which the simulation starts:
epoch: 23rd February 2020

# ######################################### World ##################################################

world_factory:
  __type__: sir_world_factory.SIRWorldFactory
  region_name: sir_region
  N: 100000

# ######################################### Seasonal Effects #######################################

seasonal_effects_model:
  __type__: void_seasonal_effects_model.VoidSeasonalEffectsModel

# ######################################### Health #################################################

health_model:
  __type__: simple_health_model.SimpleHealthModel
  beta: 1.0
  location_typ_multipliers: null
  facemask_transmission_multiplier: 1.0
  immunity_period_days: 30
  num_initial_infections_by_region_by_strain:
    'sir_region': [10]
  mutation_matrix: [[1.0]]
  number_of_strains: 1
  preset_weights_by_age: null
  health_presets: null
  # Rescale by time and population in each location, deactivate by setting sir_rescaling = False
  sir_rescaling: True
  # Deactivate by setting age_mixing_matrices = null
  age_mixing_matrices: null # Scenarios/SIR/data/age_mixing_matrices/
  age_group_interval: null # 5
  # Deactivate by setting auto_generate_presets = False
  auto_generate_presets: True
  sir_beta: 0.27 # Units: days^{-1}
  sir_gamma_inverse: 9 # Units: days
  sir_disease_level: 0.2
  sir_max_dist_days: 100 # Maximum infectiousness period, curtailing the geometric distribution

# ######################################### Movement ###############################################

movement_model:
  __type__: void_movement_model.VoidMovementModel

# ######################################### Hospitalization and Death ##############################

hospitalization_and_death_model:
  __type__: void_hospitalization_and_death_model.VoidHospitalizationAndDeathModel

# ######################################### Testing and Contact Tracing ############################

testing_and_contact_tracing_model:
  __type__: void_testing_and_contact_tracing_model.VoidTestingAndContactTracingModel

# ######################################### Vaccination ############################################

vaccination_model:
  __type__: void_vaccination_model.VoidVaccinationModel

# ######################################### Regional Mixing ########################################

regional_mixing_model:
  __type__: void_regional_mixing_model.VoidRegionalMixingModel

# ######################################### Input ##################################################

input_model:
  __type__: void_input_model.VoidInputModel

# ######################################### Output #################################################

regions_omitted_from_death_counts: []
historical_data_filepath: null

# Output that should be rendered from the simulation:
reporters:
  cli.TimeReporter: {}
  # csv.StrainCounts:
  #   filename: /tmp/strain_counts.csv
  plot.PlotInfected:
    show: False
    savefig: True
    filename: /tmp/infected_sir.png
    historical_data: null

# ######################################### Logging ################################################

# Format is https://docs.python.org/3/library/logging.config.html#logging-config-dictschema
logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    standard:
      # format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
      format: '[%(levelname)s] %(name)s: %(message)s'
  handlers:
    default:
      level: INFO
      formatter: standard
      class: logging.StreamHandler
      stream: 'ext://sys.stdout'  # Default is stderr
  loggers:
    '':   # root logger
      handlers: ['default']
      level: INFO
      propagate: False
#    'my.packg':
#      handlers: ['default']
#      level: INFO
#      propagate: False
#    '__main__':
#        handlers': ['default']
#        level: DEBUG
#        propagate: False
