---
# ######################################### Basic Parameters #######################################

# Scale factor
scale_factor: 0.25

# Profiler
profile: False
pstats_records: 100

# Random seeds for each region
random_seed: 1

# Enable or disable the use of ctypes
enable_ctypes: True

# Enable or disable the use of parallel processing. Note that the number of jobs is automatically
# reset according to the number of regions and population ratio between regions:
enable_parallel: False
num_jobs: 1

# ######################################### Clock ##################################################

# Time length of each tick in the simulation. Weeks must contain the same number of ticks, because
# we use weekly routines. This means the week length (604800) should be divisible by the following
# tick length:
tick_length_s: 600
# How long the simulation should run for, in days. Note the number of iterations will be computed
# from the tick length above:
simulation_length_days: 100
# the date at which the simulation starts:
epoch: 23th February 2020

# ######################################### World ##################################################

world_factory:
  __type__: abmlux_world_factory.ABMluxWorldFactory
  # The file path from where to load the world file
  world_fp: Scenarios/Luxembourg/data/sim_factory.abm
  region_name: Luxembourg

# ######################################### Seasonal Effects #######################################

seasonal_effects_model:
  __type__: void_seasonal_effects_model.VoidSeasonalEffectsModel

# ######################################### Health #################################################

# Disease (mutation viewed from the point of view of within-host competition, for the case in which
# strains can be ordered by within-host fitness). Cross immunity is represented by the off-diagonal
# step functions. Furthermore tau refers to the set of possible outcomes, while rho refers to the
# probability distribution over these outcomes. For simplicity we assume only two possible outcomes.
# Note that the infectiousness probability give a probability per tick, and must therefore be
# adjusted if the tick length is changed.

health_model:
  __type__: simple_health_model.SimpleHealthModel
  location_typ_multipliers: # Unless specfified set to 1.0
    Outdoor: 0.0
    Belgium: 0.0
    France: 0.0
    Germany: 0.0
    Construction: 0.0
    Cemetery: 0.0
  divide_location_multipliers_by_number_of_agents_in_region: False
  facemask_transmission_multiplier: 0.1
  immunity_period_days: 7
  num_initial_infections_by_region_by_strain:
    'Luxembourg': [320, 0]
  mutation_matrix: [[0.99, 0.01], [0.0, 1.0]]
  number_of_strains: 2
  preset_weights_by_age:
    0:  {preset_0: 1.00, preset_1: 0.00}
    18: {preset_0: 0.99, preset_1: 0.01}
    65: {preset_0: 0.98, preset_1: 0.02}
  health_presets:
    preset_0:
      0:
        rho_immunity_failure:
          [[[[-1, 5, 300], [[1.0, 0.0], [0.5, 0.0], [1.0, 0.0]]],
            [[-1, 5, 300], [[1.0, 0.0], [0.5, 0.0], [1.0, 0.0]]]],
           [[[-1, 5, 300], [[1.0, 0.0], [0.5, 0.0], [1.0, 0.0]]],
            [[-1, 5, 300], [[1.0, 0.0], [0.5, 0.0], [1.0, 0.0]]]]]
        sigma_immunity_failure:
          [[[[-1, 5, 300], [1.0, 0.5, 1.0]],
            [[-1, 5, 300], [1.0, 0.5, 1.0]]],
           [[[-1, 5, 300], [1.0, 0.5, 1.0]],
            [[-1, 5, 300], [1.0, 0.5, 1.0]]]]
        infectiousness:
          [[[-1, 0, 5], [0.0, 0.00035, 0.0]],
           [[-1, 0, 5], [0.0, 0.00035, 0.0]]]
        disease:
          [[[-1, 0, 5], [0.0, 0.2, 0.0]],
           [[-1, 0, 5], [0.0, 0.2, 0.0]]]
        strain:
          [[[-1, 0, 5], [-1, 0, -1]],
           [[-1, 0, 5], [-1, 1, -1]]]
      1:
        rho_immunity_failure:
          [[[[-1, 7, 300], [[1.0, 0.0], [0.5, 0.0], [1.0, 0.0]]],
            [[-1, 7, 300], [[1.0, 0.0], [0.5, 0.0], [1.0, 0.0]]]],
           [[[-1, 7, 300], [[1.0, 0.0], [0.5, 0.0], [1.0, 0.0]]],
            [[-1, 7, 300], [[1.0, 0.0], [0.5, 0.0], [1.0, 0.0]]]]]
        sigma_immunity_failure:
          [[[[-1, 7, 300], [1.0, 0.5, 1.0]],
            [[-1, 7, 300], [1.0, 0.5, 1.0]]],
           [[[-1, 7, 300], [1.0, 0.5, 1.0]],
            [[-1, 7, 300], [1.0, 0.5, 1.0]]]]
        infectiousness:
          [[[-1, 0, 7], [0.0, 0.00035, 0.0]],
           [[-1, 0, 7], [0.0, 0.00035, 0.0]]]
        disease:
          [[[-1, 0, 2, 4, 7], [0.0, 0.2, 0.5, 0.2, 0.0]],
           [[-1, 0, 2, 4, 7], [0.0, 0.2, 0.5, 0.2, 0.0]]]
        strain:
          [[[-1, 0, 7], [-1, 0, -1]],
           [[-1, 0, 7], [-1, 1, -1]]]
    preset_1:
      0:
        rho_immunity_failure:
          [[[[-1, 5, 300], [[1.0, 0.0], [0.5, 0.0], [1.0, 0.0]]],
            [[-1, 5, 300], [[1.0, 0.0], [0.5, 0.0], [1.0, 0.0]]]],
           [[[-1, 5, 300], [[1.0, 0.0], [0.5, 0.0], [1.0, 0.0]]],
            [[-1, 5, 300], [[1.0, 0.0], [0.5, 0.0], [1.0, 0.0]]]]]
        sigma_immunity_failure:
          [[[[-1, 5, 300], [1.0, 0.5, 1.0]],
            [[-1, 5, 300], [1.0, 0.5, 1.0]]],
           [[[-1, 5, 300], [1.0, 0.5, 1.0]],
            [[-1, 5, 300], [1.0, 0.5, 1.0]]]]
        infectiousness:
          [[[-1, 0, 5], [0.0, 0.00035, 0.0]],
           [[-1, 0, 5], [0.0, 0.00035, 0.0]]]
        disease:
          [[[-1, 0, 5], [0.0, 0.2, 0.0]],
           [[-1, 0, 5], [0.0, 0.2, 0.0]]]
        strain:
          [[[-1, 0, 5], [-1, 0, -1]],
           [[-1, 0, 5], [-1, 1, -1]]]
      1:
        rho_immunity_failure:
          [[[[-1, 7, 300], [[1.0, 0.0], [0.5, 0.0], [1.0, 0.0]]],
            [[-1, 7, 300], [[1.0, 0.0], [0.5, 0.0], [1.0, 0.0]]]],
           [[[-1, 7, 300], [[1.0, 0.0], [0.5, 0.0], [1.0, 0.0]]],
            [[-1, 7, 300], [[1.0, 0.0], [0.5, 0.0], [1.0, 0.0]]]]]
        sigma_immunity_failure:
          [[[[-1, 7, 300], [1.0, 0.5, 1.0]],
            [[-1, 7, 300], [1.0, 0.5, 1.0]]],
           [[[-1, 7, 300], [1.0, 0.5, 1.0]],
            [[-1, 7, 300], [1.0, 0.5, 1.0]]]]
        infectiousness:
          [[[-1, 0, 7], [0.0, 0.00035, 0.0]],
           [[-1, 0, 7], [0.0, 0.00035, 0.0]]]
        disease:
          [[[-1, 0, 2, 4, 7], [0.0, 0.2, 0.5, 0.2, 0.0]],
           [[-1, 0, 2, 4, 7], [0.0, 0.2, 0.5, 0.2, 0.0]]]
        strain:
          [[[-1, 0, 7], [-1, 0, -1]],
           [[-1, 0, 7], [-1, 1, -1]]]

# ######################################### Movement ###############################################

movement_model:
  __type__: simple_movement_model.SimpleMovementModel
  weighted_sampling: False
  home_activity: "House"
  location_closure_exemptions:
    House: ["House"]
  facemask_activities: ["Public Transport"]
  age_groups:         [  0,  18,  65]
  facemask_hesitancy: [0.9, 0.5, 0.2]

# ######################################### Hospitalization and Death ##############################

hospitalization_and_death_model:
  __type__: void_hospitalization_and_death_model.VoidHospitalizationAndDeathModel

# ######################################### Testing and Contact Tracing ############################

testing_and_contact_tracing_model:
  __type__: void_testing_and_contact_tracing_model.VoidTestingAndContactTracingModel

# ######################################### Vaccination ############################################

vaccination_model:
  __type__: void_vaccination_model.VoidVaccinationModel

# ######################################### Regional Mixing ########################################

regional_mixing_model:
  __type__: void_regional_mixing_model.VoidRegionalMixingModel

# ######################################### Input ##################################################

input_model:
  __type__: void_input_model.VoidInputModel

# ######################################### Output #################################################

# Output that should be rendered from the simulation:
reporters:
  cli.TimeReporter: {}
  csv.StrainCounts:
    filename: /tmp/strain_counts.csv
  plot.PlotInfected:
    show: False
    savefig: True
    filename: /tmp/infected.png

# ######################################### Logging ################################################

# Format is https://docs.python.org/3/library/logging.config.html#logging-config-dictschema
logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    standard:
      # format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
      format: '[%(levelname)s] %(name)s: %(message)s'
  handlers:
    default:
      level: INFO
      formatter: standard
      class: logging.StreamHandler
      stream: 'ext://sys.stdout'  # Default is stderr
  loggers:
    '':   # root logger
      handlers: ['default']
      level: INFO
      propagate: False
#    'my.packg':
#      handlers: ['default']
#      level: INFO
#      propagate: False
#    '__main__':
#        handlers': ['default']
#        level: DEBUG
#        propagate: False
