---
# ######################################### Basic Parameters #######################################

# Scale factor
scale_factor: 0.0005

# Profiler
profile: False
pstats_records: 100

# Random seeds for each region
random_seed: 131

# Enable or disable the use of parallel processing. Note that the number of jobs is automatically
# reset according to the number of regions and population ratio between regions:
enable_parallel: True
num_jobs: -2

# ######################################### Clock ##################################################

# Time length of each tick in the simulation. The day length (86400) should be divisible by the
# following tick length:
tick_length_s: 28800
# How long the simulation should run for, in days. Note the number of iterations will be computed
# from the tick length above:
simulation_length_days: 365
# the date at which the simulation starts:
epoch: 1st January 2020                                                                             # POSSIBLE FREE VARIABLE

# ######################################### World ##################################################

world_factory:
  __type__: heterogeneous_world_factory.HeterogeneousWorldFactory
  random_seed: 1
  regions_data_file:
    Scenarios/Heterogeneous/data/country_data.csv
  regions_shape_data_file:
    Scenarios/Heterogeneous/data/country_data_shapefiles/CNTR_RG_60M_2020_4326.shp
  population_dist_data_folder:
    Scenarios/Heterogeneous/data/country_data_population_distribution/processed/density_grids
  population_id_data_folder:
    Scenarios/Heterogeneous/data/country_data_population_distribution/processed/id_grids
  # Regions to simulate. If list empty, simulates all regions.
  regions_to_simulate: ['GB'] # ['KP', 'KR'] # ['FR', 'BE', 'LU', 'DE', 'GB', 'NL', 'IE']
  # Locations
  house_location_type: House
  square_location_type: Square
  # Movement
  local_sample_size: 500
  nonlocal_sample_size: 500
  num_locs_for_community_activity: 10
  gravity_model_exponent: 0.5
  # Activities
  home_activity: Home_Activity
  community_activity: Community_Activity
  min_age_community_activity: 4
  max_age_community_activity: 64
  # Travel Matrix
  local_travel_prob_per_day: 0.0
  distance_threshold: 10
  airport_data_file:
    Scenarios/Heterogeneous/data/airport_data.csv
  air_travel_data_file:
    Scenarios/Heterogeneous/data/air_travel_data.csv

# ######################################### Seasonal Effects #######################################

seasonal_effects_model:
  __type__: default_seasonal_effects_model.DefaultSeasonalEffectsModel
  # If the following is null, as opposed to a filepath, all multipliers are set equal to 1:
  seasonal_multiplier_by_region_by_month: Scenarios/Heterogeneous/data/country_data_seasonality.csv
  out_of_season_multiplier: 0.75                                                                    # POSSIBLE FREE VARIABLE

# ######################################### Health #################################################

health_model:
  __type__: default_health_model.DefaultHealthModel
  beta: [0.065]                                                                                     # POSSIBLE FREE VARIABLE
  location_typ_multipliers:
    Square: 0.2                                                                                     # POSSIBLE FREE VARIABLE
    House: 1.0
  facemask_transmission_multiplier: 1.0
  immunity_period_days: 30
  num_initial_infections_by_region_by_strain:
    'GB': [100000]                                                                                  # POSSIBLE FREE VARIABLE (ALSO IMMUNE DURATION?)
  mutation_matrix: [[1.0]]
  number_of_strains: 1
  preexisting_sigma_multiplier: 0.5                                                                 # POSSIBLE FREE VARIABLE
  preexisting_rho_multiplier: 0.5                                                                   # POSSIBLE FREE VARIABLE
  country_data_sigma_immunity_fp:
    Scenarios/Heterogeneous/data/immunity_data/country_data_sigma_immunity.csv
  country_data_rho_immunity_fp:
    Scenarios/Heterogeneous/data/immunity_data/country_data_rho_immunity.csv
  preset_weights_by_age:
    0:  {preset_0: 1.0000, preset_1: 0.0000}
    5:  {preset_0: 0.9999, preset_1: 0.0001}
    10: {preset_0: 0.9999, preset_1: 0.0001}
    15: {preset_0: 0.9998, preset_1: 0.0002}
    20: {preset_0: 0.9998, preset_1: 0.0002}
    25: {preset_0: 0.9996, preset_1: 0.0004}
    30: {preset_0: 0.9994, preset_1: 0.0006}
    35: {preset_0: 0.9991, preset_1: 0.0009}
    40: {preset_0: 0.9985, preset_1: 0.0015}
    45: {preset_0: 0.9977, preset_1: 0.0023}
    50: {preset_0: 0.9964, preset_1: 0.0036}
    55: {preset_0: 0.9943, preset_1: 0.0057}
    60: {preset_0: 0.9911, preset_1: 0.0089}
    65: {preset_0: 0.9861, preset_1: 0.0139}
    70: {preset_0: 0.9783, preset_1: 0.0217}
    75: {preset_0: 0.9661, preset_1: 0.0339}
    80: {preset_0: 0.9470, preset_1: 0.0530}
    85: {preset_0: 0.9172, preset_1: 0.0828}
    90: {preset_0: 0.8381, preset_1: 0.1619}
  health_presets:
    preset_0:
      0:
        rho_immunity_failure:
          [[[[-1, 15, 30, 90, 180], [[1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1.0, 0.0]]]]]
        sigma_immunity_failure:
          [[[[-1, 15, 30, 90, 135, 180], [1.0, 0.0, 0.0, 0.35, 0.55, 0.90]]]]
        infectiousness:
          [[[-1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
            [0.000000000, 0.000000000, 0.000000000, 0.000177828, 0.007943284,
             0.562341455, 1.000000000, 0.944061094, 0.794328418, 0.562341455,
             0.316227839, 0.177827982, 0.079432842, 0.031622784, 0.010000002,
             0.004466837, 0.000000000]]]
        disease:
          [[[-1, 0, 15], [0.0, 0.15, 0.0]]]
        strain:
          [[[-1, 0, 15], [-1, 0, -1]]]
      1:
        rho_immunity_failure:
          [[[[-1, 15, 30, 90, 180], [[1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1.0, 0.0]]]]]
        sigma_immunity_failure:
          [[[[-1, 15, 30, 90, 135, 180], [1.0, 0.0, 0.0, 0.35, 0.55, 0.90]]]]
        infectiousness:
          [[[-1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
            [0.000000000, 0.000000000, 0.000000000, 0.000177828, 0.007943284,
             0.562341455, 1.000000000, 0.944061094, 0.794328418, 0.562341455,
             0.316227839, 0.177827982, 0.079432842, 0.031622784, 0.010000002,
             0.004466837, 0.000000000]]]
        disease:
          [[[-1, 0, 15], [0.0, 0.15, 0.0]]]
        strain:
          [[[-1, 0, 15], [-1, 0, -1]]]
    preset_1:
      0:
        rho_immunity_failure:
          [[[[-1, 15, 30, 90, 180], [[1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1.0, 0.0]]]]]
        sigma_immunity_failure:
          [[[[-1, 15, 30, 90, 135, 180], [1.0, 0.0, 0.0, 0.35, 0.55, 0.90]]]]
        infectiousness:
          [[[-1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
            [0.000000000, 0.000000000, 0.000000000, 0.000177828, 0.007943284,
             0.562341455, 1.000000000, 0.944061094, 0.794328418, 0.562341455,
             0.316227839, 0.177827982, 0.079432842, 0.031622784, 0.010000002,
             0.004466837, 0.000000000]]]
        disease:
          [[[-1, 0, 15], [0.0, 0.15, 0.0]]]
        strain:
          [[[-1, 0, 15], [-1, 0, -1]]]
      1:
        rho_immunity_failure:
          [[[[-1, 15, 30, 90, 180], [[1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1.0, 0.0]]]]]
        sigma_immunity_failure:
          [[[[-1, 15, 30, 90, 135, 180], [1.0, 0.0, 0.0, 0.35, 0.55, 0.90]]]]
        infectiousness:
          [[[-1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
            [0.000000000, 0.000000000, 0.000000000, 0.000177828, 0.007943284,
             0.562341455, 1.000000000, 0.944061094, 0.794328418, 0.562341455,
             0.316227839, 0.177827982, 0.079432842, 0.031622784, 0.010000002,
             0.004466837, 0.000000000]]]
        disease:
          [[[-1, 0, 15], [0.0, 0.15, 1.0]]]
        strain:
          [[[-1, 0, 15], [-1, 0, -1]]]
  # Rescale by time and population in each location, deactivate by setting sir_rescaling = False. If
  # activated, can still deactivate age mixing by setting age_mixing_matrices = null
  sir_rescaling: False
  age_mixing_matrices: null
  age_group_interval: 5
  # Deactivate by setting auto_generate_presets = False
  auto_generate_presets: False
  sir_beta: null # Units: days^{-1}
  sir_gamma_inverse: null # Units: days
  sir_disease_level: null
  sir_max_dist_days: null # Maximum infectiousness period, curtailing the geometric distribution 

# ######################################### Movement ###############################################

movement_model:
  __type__: default_movement_model.DefaultMovementModel
  weighted_sampling: True
  home_activity: "Home_Activity"
  location_closure_exemptions:
    House: ["Home_Activity"]
  facemask_activities: [Other_Activity]
  age_groups:         [  0,  18,  65]
  facemask_hesitancy: [0.9, 0.5, 0.2]

# ######################################### Hospitalization and Death ##############################

hospitalization_and_death_model:
  __type__: void_hospitalization_and_death_model.VoidHospitalizationAndDeathModel

# ######################################### Testing and Contact Tracing ############################

testing_and_contact_tracing_model:
  __type__: void_testing_and_contact_tracing_model.VoidTestingAndContactTracingModel

# ######################################### Vaccination ############################################

vaccination_model:
  __type__: default_vaccination_model.DefaultVaccinationModel
  number_of_vaccines: 1
  age_groups:        [  0,  18,  65]
  vaccine_hesitancy: [0.8, 0.4, 0.1]
  booster_waiting_time_days: 50
  vaccines:
    vaccine_0:
      rho_immunity_failure:
        [[[-1, 0, 30, 90, 180], [[1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1.0, 0.0]]]]
      sigma_immunity_failure:
        [[[-1, 0, 30, 90, 180], [1.0, 0.5, 0.6, 0.75, 0.90]]]

# ######################################### Regional Mixing ########################################

travel_model:
  __type__: void_travel_model.VoidTravelModel

# ######################################### Policy Maker ###########################################

policy_maker_model:
  __type__: optimization_policy_maker_model.OptimizationPolicyMakerModel

# ######################################### Output #################################################

regions_omitted_from_death_counts: ['CN', 'KP']
super_regions_omitted_from_deaths_counts: ['Africa', 'Asia']
historical_data_filepath: Scenarios/Heterogeneous/data/historical_data/WHO-COVID-19-global-data.csv

# Output that should be rendered from the simulation:
reporters:
  # cli.TimeReporter: {}
  # csv.StrainCounts:
  #   filename: /tmp/strain_counts.csv
  # plot.PlotInfected:
  #   show: False
  #   savefig: True
  #   filename: /tmp/infected_heterogeneous.png
  #   historical_data: null
  plot.PlotDeaths:
    show: False
    savefig: True
    daily_deaths_filename: /tmp/daily_deaths_heterogeneous.png
    cumulative_deaths_filename: /tmp/cumulative_deaths_heterogeneous.png
    deaths_by_country_filename: /tmp/deaths_by_region.csv
    historical_data: null
  # pygame_shapes.PygameShapes:
  #   fullscreen: True
  #   font_size: 20
  #   max_norm_prev: 1.0
  #   refresh_rate: 60
  #   display_width: 1500
  #   display_height: 700
  #   points_per_polygon: 400
  #   cmap: "Oranges"
  # pygame_coords.PygameCoords:
  #   fullscreen: True
  #   font_size: 20
  #   plot_prevalence: False
  #   max_prev_to_plot: 1.0
  #   plot_num_infected: True
  #   max_num_inf_to_plot: 10
  #   refresh_rate: 60
  #   display_width: 1500
  #   display_height: 700
  #   cellsize: 0.0416666666667
  #   cmap: "Oranges"

# ######################################### Logging ################################################

# Format is https://docs.python.org/3/library/logging.config.html#logging-config-dictschema
logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    standard:
      # format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
      format: '[%(levelname)s] %(name)s: %(message)s'
  handlers:
    default:
      level: INFO
      formatter: standard
      class: logging.StreamHandler
      stream: 'ext://sys.stdout'  # Default is stderr
  loggers:
    '':   # root logger
      handlers: ['default']
      level: INFO
      propagate: False
#    'my.packg':
#      handlers: ['default']
#      level: INFO
#      propagate: False
#    '__main__':
#        handlers': ['default']
#        level: DEBUG
#        propagate: False
